name: Build and Push Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (g++)
      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      # Step 3: Build the test.cpp file
      - name: Build test.cpp
        run: g++ -o test test.cpp

      # Step 4: Set up Git with the GIT_KEY secret and configure user info
      - name: Configure Git
        run: |
          git config --global user.name "imjafran"
          git config --global user.email "exjafran@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_KEY }}@github.com/imjafran/testsh.git

      # Step 5: Create and push the build branch
      - name: Commit and Push Executable
        run: |
          git checkout -b build
          mv test ./built-test
          git add ./built-test
          git commit -m "Add built executable"
          git push -u origin build
